### ISSUE TITLE
登录接口

### ISSUE THREAD

**Issue by weipengcheng1** [jasonLaw1015/GfEasy#1]
代码中缺少登录的接口
![image](https://user-images.githubusercontent.com/49983314/134525402-aa582ce3-f067-4301-95d2-9ced08f846ae.png)
请检查代码的完整性

**Comment by jasonLaw1015** [comment]
这个是cooladmin生成接口访问出了问题，我之前也遇到。你可以换下node版本，然后删除node_modules，安装node 14.17.6版本，重新安装依赖一下  yarn 
当访问的是 /admin/baseOpen/captcha接口，你就成功了

**Comment by jasonLaw1015** [comment]
尽量node版本高一点。装nvm，换node版本还挺容易

**Comment by weipengcheng1** [comment]
![image](https://user-images.githubusercontent.com/49983314/134688159-2c0efdcf-a984-4730-bb91-af0092eee6d3.png)
node版本已经是最高的了

**Comment by jasonLaw1015** [comment]
换成node 14.17.6版本试下，记得删除node_modules后再重新安装依赖

**Comment by weipengcheng1** [comment]
不行的，我现在版本已经是14.17.6

**Comment by jasonLaw1015** [comment]
> 不行的，我现在版本已经是14.17.6

你的是什么系统？
有删了nodel_modules，再重装吗。

npm install 或 yarn 分别试下

实在不行就换个node >=12.0.0版本重试下上面步骤

**Comment by weipengcheng1** [comment]
win10系统，都不知道删了多少遍了，node也换了三个版本了

**Comment by jasonLaw1015** [comment]
![image](https://user-images.githubusercontent.com/28339015/134699563-24458d79-0394-4192-a2ab-d67e02313398.png)
在这个src\core\service\base.ts文件中
你去这个打日志，看看 this.namespace有没有值

**Comment by jasonLaw1015** [comment]
找到原因了，迟点我修复一下。修复好通知你再弄

**Comment by jasonLaw1015** [comment]
修复了，现在可以了，我用windows机器试也过了。重新拉一下GfEasyAdmin的代码，删了本地node_modules，用yarn安装依赖。接着yarn dev运行即可

**Comment by weipengcheng1** [comment]
此项目是一定要使用yarn来安装依赖吗

**Comment by jasonLaw1015** [comment]
mac的npm和yarn都行。Windows下，你也可以试下npm ，刚刚我Windows试了下npm，有点小问题，尽量用yarn吧。
这样安装下吧
npm i -g yarn
