### ISSUE TITLE
大家不要买,免费的在这

### ISSUE THREAD

**Issue by liujianying** [jasonLaw1015/GfEasy#3]
https://zhuanlan.zhihu.com/p/357799195

**Comment by jasonLaw1015** [comment]
不想支付，每天有三次免费生成机会也够你们用了吧。他没代码生成

**Comment by jasonLaw1015** [comment]
才199，终生免费使用反应那么大。你可以不用代码生成模块就好了，也跟那个一样了。go还性能强大点，可编译成二进制文件。
