### ISSUE TITLE
为什么代码生成还要限制三次

### ISSUE THREAD

**Issue by Hareis** [jasonLaw1015/GfEasy#4]
为什么代码生成还要限制三次

**Comment by jasonLaw1015** [comment]
每天限制三次，是因为作者想不开，想赚咖啡钱。结果咖啡豆都没赚到，留下的后遗症。(: )～

**Comment by Hareis** [comment]
> 每天限制三次，是因为作者想不开，想赚咖啡钱。结果咖啡豆都没赚到，留下的后遗症。(: )～

不如去掉限制  卖生成的源码 ？？

**Comment by jasonLaw1015** [comment]
近期准备去掉这个限制

**Comment by jasonLaw1015** [comment]
已经取消了这个限制了，拉取新的代码就行
